spring:
   profiles:
       active:
        - dev
---
server:
    port:  7001 

spring:
  profiles:  dev
  application:
      name:  microservicecloud-config-eureka-client

eureka:
    instance:
       hostname:  eureka7001.com
    client: 
       register_with_eureka: false     #false表示不向注册中心注册自己。
       fetch_registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
       service_url: 
             defaultZone:  http://eureka7001.com:7001/eureka/
---
server:
    port:  7001 

spring:
  profiles:  test
  application:
      name:  microservicecloud-config-eureka-client

eureka:
    instance:
       hostname:  eureka7001.com
    client: 
       register_with_eureka: false     #false表示不向注册中心注册自己。
       fetch_registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
       service_url: 
             defaultZone:  http://eureka7001.com:7001/eureka/
